file = open('./references/items_list.txt', 'r')
contents = file.readlines()
file.close()
contents.pop()
contents.sort()
file = open('./references/items_list.txt', 'w')
file.write(''.join(contents))
file.close()
